In [ ]:
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(threshold=np.inf) #show all elements when using print

In [ ]:
#introducing numpy arrays - fixed number of entries of same type (e.g. 1D array filled with integers of length 10)
#1D array
arr=np.array([1,2,3,4,5,6,7,8,9,10]) #initialize numpy array from list
print(arr) #print array
print('')

print(arr[1]) #print single entry
print('')

print(arr.sum()) #prints sum of all array entries
print('')

linarray=np.arange(0,20) #create 1D array with increasing numbers from 0 to 19
print(linarray)

In [39]:
#2D array
matrix_simple=np.full((3,5),0) #create 2D 3x5 array filled with 0's
print(matrix_simple)
print('')

matrix_simple[1,2]=1 #set single entry to 1
print(matrix_simple)
print('')

matrix_test = linarray.reshape(5,4) #reshape 1D array into 2D array
print(matrix_test)
print('')

print(matrix_test[1]) #print single row of 2D array
print('')

print(matrix_test[1,2]) #print single entry of 2D array

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[4 5 6 7]

6


In [ ]:
np.random.seed(10) #set seed for pseudo-random number generator

In [ ]:
#use random library in numpy
print(np.random.random()) #generates random number between [0,1)
print('')

print(np.random.randint(5,10)) #generates random integer between [5,10)
print('')

np.random.shuffle(arr) #randomly shuffles array in-place
print(arr)
print('')

print(arr.sum()) #sum remains unchanged

In [ ]:
#Try it out yourself!
#Generate an array of length 100 filled with random integers between 1 and 3 (inclusive). What is the sum of all the numbers in that list?


In [ ]:
def multi_dice_throw(number_dice, type_dice=6):
    '''
    This function simulates a multi dice throw with number_dice number of dice at the same time 

    Parameters: 
    number_dice (int): number of dice being thrown
    type_dice=6 (int): number of sides of the dice, which corresponds to highest number that can be obtained with a single dice

    Output: Sum of all dice
    '''
    

In [ ]:
def multi_multi_dice_throw(number_throws, number_dice=1, type_dice=6):
    '''
    This function simulates number_throws throws with number_dice number of dice

    Parameters: 
    number_throws (int): number of multiple dice throws
    number_dice (int): number of dice being thrown
    type_dice=6 (int): number of sides of the dice, which corresponds to highest number that can be obtained with a single dice

    Output: numpy array of length number_throws with the sum of dice of each throw as entries 
    '''
    

In [ ]:
#Main program 
type_dice=6 #number of dice sides
number_dice=3 #number of dice in single throw
number_throws=100000 #number of throws

statistic=multi_multi_dice_throw(number_throws, number_dice, type_dice)

#Output
plt.figure() #generate new figure
plt.hist(statistic, bins=range(1,type_dice*number_dice+2), rwidth=0.8, align='left')
plt.xlabel('Sum of dice throws') 
plt.ylabel('Number of throws')

plt.title('Histogram for throw of {} {}er-dice'.format(number_dice, type_dice))
plt.show() 